#include "main.h"
#include "gba.h"

#include <stdio.h>
#include <stdlib.h>

#include "images/cards_c/cards_white.c"


/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

// Load initial application state
// enum gba_state state = START;

// List of every possible card in the deck
struct PLAY_CARD ace_clubs = {ace_clubs_white, CLUBS, ACE};
// struct PLAY_CARD two_clubs = {two_clubs_white, CLUBS, TWO};
// UNUSED(two_clubs);

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    waitForVBlank();
    fillScreenDMA(BLACK);
    // fillScreenDMA works
    int r = randint(0, 160);
    int c = randint(0, 240);
    waitForVBlank();
    drawRectDMA(r, c, 10, 10, RED);
    delay(5);
    waitForVBlank();
    drawRectDMA(r, c, 10, 10, WHITE);
    delay(5);
    waitForVBlank();
    // drawImageDMA(0,0, GARBAGE_WIDTH, GARBAGE_HEIGHT, garbage);
    drawImageDMA(0,0, CARD_WIDTH, CARD_HEIGHT, ace_clubs.image);
    delay(5);


    waitForVBlank();
    // drawImageDMA(0, 50, GARBAGE_HEIGHT, GARBAGE_WIDTH, garbage);
    delay(5);
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // switch (state) {
    //   case START:

    //     // state = ?
    //     break;
    //   case PLAY:

    //     // state = ?
    //     break;
    //   case WIN:

    //     // state = ?
    //     break;
    //   case LOSE:

    //     // state = ?
    //     break;
    // }
    waitForVBlank();
    fillScreenDMA(YELLOW);
    delay(5);
    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(previousButtons); // You can remove this once previousButtons is used
  return 0;
}
