#include "main.h"
#include "gba.h"

#include <stdio.h>
#include <stdlib.h>

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

enum cards_state{
  card_1 = 0,
  card_2 = 1,
  card_3 = 2,
  card_4 = 3
};

// for intents and purposes, main() is simultaneously an init() function and a rendering function
int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  struct DECK deck;
  add_cards_to_deck(&deck);
  // Load initial application state
  // enum gba_state state = START;
  enum cards_state state = card_1;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    waitForVBlank();
    fillScreenDMA(BLACK);
    switch(state){
      case card_1:
        waitForVBlank();
        drawImageDMA(0,0, CARD_WIDTH, CARD_HEIGHT, deck.cards[randint(0,52)].image);
        break;
      case card_2:
        waitForVBlank();
        drawImageDMA(0,30, CARD_WIDTH, CARD_HEIGHT, deck.cards[randint(0,52)].image);
        break;
      case card_3:
        waitForVBlank();
        drawImageDMA(0,60, CARD_WIDTH, CARD_HEIGHT, deck.cards[randint(0,52)].image);
        break;
      case card_4:
        waitForVBlank();
        drawImageDMA(0,90, CARD_WIDTH, CARD_HEIGHT, deck.cards[randint(0,52)].image);
        break;
    }
    state = randint(0,4);
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // switch (state) {
    //   case START:

    //     // state = ?
    //     break;
    //   case PLAY:

    //     // state = ?
    //     break;
    //   case WIN:

    //     // state = ?
    //     break;
    //   case LOSE:

    //     // state = ?
    //     break;
    // }
    delay(50);
    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(previousButtons); // You can remove this once previousButtons is used
  return 0;
}
// Add all of the cards to the deck
void add_cards_to_deck(struct DECK * deck){
    deck->cards[0] = ace_clubs;
    deck->cards[1] = two_clubs;
    deck->cards[2] = three_clubs;
    deck->cards[3] = four_clubs;
    deck->cards[4] = five_clubs;
    deck->cards[5] = six_clubs;
    deck->cards[6] = seven_clubs;
    deck->cards[7] = eight_clubs;
    deck->cards[8] = nine_clubs;
    deck->cards[9] = ten_clubs;
    deck->cards[10] = jack_clubs;
    deck->cards[11] = queen_clubs;
    deck->cards[12] = king_clubs;

    deck->cards[13] = ace_diamonds;
    deck->cards[14] = two_diamonds;
    deck->cards[15] = three_diamonds;
    deck->cards[16] = four_diamonds;
    deck->cards[17] = five_diamonds;
    deck->cards[18] = six_diamonds;
    deck->cards[19] = seven_diamonds;
    deck->cards[20] = eight_diamonds;
    deck->cards[21] = nine_diamonds;
    deck->cards[22] = ten_diamonds;
    deck->cards[23] = jack_diamonds;
    deck->cards[24] = queen_diamonds;
    deck->cards[25] = king_diamonds;

    deck->cards[26] = ace_hearts;
    deck->cards[27] = two_hearts;
    deck->cards[28] = three_hearts;
    deck->cards[29] = four_hearts;
    deck->cards[30] = five_hearts;
    deck->cards[31] = six_hearts;
    deck->cards[32] = seven_hearts;
    deck->cards[33] = eight_hearts;
    deck->cards[34] = nine_hearts;
    deck->cards[35] = ten_hearts;
    deck->cards[36] = jack_hearts;
    deck->cards[37] = queen_hearts;
    deck->cards[38] = king_hearts;

    deck->cards[39] = ace_spades;
    deck->cards[40] = two_spades;
    deck->cards[41] = three_spades;
    deck->cards[42] = four_spades;
    deck->cards[43] = five_spades;
    deck->cards[44] = six_spades;
    deck->cards[45] = seven_spades;
    deck->cards[46] = eight_spades;
    deck->cards[47] = nine_spades;
    deck->cards[48] = ten_spades;
    deck->cards[49] = jack_spades;
    deck->cards[50] = queen_spades;
    deck->cards[51] = king_spades;
}